config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, path: '', path_names: { sign_in: 'login',
              sign_out: 'logout', sign_up: 'register' },
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friendships, only: %i[create update destroy]
  resources :films, only: %i[index show] do
    resources :reviews, only: %i[index show new create]
  end
  resources :people, only: [:show]
  resources :news
  resources :libraries
  resources :users, only: %i[index show]

  mount ActionCable.server => '/cable'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  firstname              :string
#  lastname               :string
#  birthday               :date
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  roles                  :string
#

class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: %i[admin editor], multiple: false) ##
  ############################################################################################

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :omniauthable,
          omniauth_providers: %i[facebook]

  validates :firstname, :lastname, length: { maximum: 30 }
  validates :nickname, presence: true, length: { minimum: 3, maximum: 15 }

  extend FriendlyId
  friendly_id :nickname, use: :slugged

  has_many :friendships
  has_many :received_friendships, class_name: 'Friendship', foreign_key: 'friend_id'

  has_many :active_friends, -> { where(friendships: { accepted: true }) }, through: :friendships, source: :friend
  has_many :received_friends, -> { where(friendships: { accepted: true }) }, through: :received_friendships, source: :user
  has_many :pending_friends, -> { where(friendships: { accepted: false }) }, through: :friendships, source: :friend
  has_many :requested_friendships, -> { where(friendships: { accepted: false }) }, through: :received_friendships, source: :user

  has_many :libraries, dependent: :destroy
  has_many :films_seen, -> { Library.seen }, through: :libraries, source: :film
  has_many :films_to_see, -> { Library.to_see }, through: :libraries, source: :film

  has_many :news, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.nickname = auth.info.name
      user.firstname = auth.info.first_name   # assuming the user model has a name
      user.lastname = auth.info.last_name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def name
    if !firstname.nil? || !lastname.nil?
      "#{firstname} #{lastname}"
    else
      'User'
    end
  end

  def friends
    active_friends | received_friends
  end

  def pending
    pending_friends | requested_friendships
  end

  def friends_with?(user)
    friends.include?(user)
  end

  def friendship_with(user)
    Friendship.where('user_id = ? OR friend_id = ?', user.id, user.id).first
  end

  def friendship_requests
    Friendship.where(friend_id: id, accepted: false)
  end

  def films
    films_seen | films_to_see
  end

  def film_review(film)
    reviews.where(film: film)
  end

  def average_rating
    reviews.average(:rating).to_f.round(1)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  access all: [:show], user: :all

  def index
    @users = User.all
  end

  def show
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_user.html.haml
.col-sm-6
  .user-partial
    .row
      .col-md-3
        = gravatar_for(user, size: 80)
      .col-md-5
        .size-80= link_to user.name, user
        .size-80= user.birthday
      .col-md-4
        - if current_user.friends_with?(user)
          = button_to 'Delete friend', friendship_path(id: current_user.friendship_with(user).id), method: :delete, class: 'btn btn-danger'
        - elsif current_user.pending.include?(user)
          = "Requested friendship"
        - else
          = button_to 'Add friend', friendships_path(friend_id: user), method: :post, class: 'btn btn-primary' unless user.eql?(current_user)
  %hr

app/views/users/index.html.haml
.container
  %h1.text-center.font-weight-bold Users
  .row
    = render @users

app/views/users/show.html.haml
.container
  .user-profile
    .row
      .col-md-3
        = gravatar_for(@user, size: 160)
        %br
        %h4= @user.name
        .row
          .col-md-3
            = "Birthday:"
          .col-md-6
            = @user.birthday
        %h4 Friends
        - @user.friends.in_groups_of(2, false) do |group|
          .row
            - group.each do |friend|
              .col-md-4.user-friend
                = gravatar_for(friend, size: 50)
                %p.size-80= link_to friend.name, friend
      .col-md-5
        %h2.font-weight-bold= "#{@user.name}'s reviews"
        = render @user.reviews
      .col-md-4
        %h2.font-weight-bold Average film rating:
        %p.size-120
          = @user.average_rating
          |
          %span.rating-count
            = pluralize(@user.reviews.size, 'vote')
        %h2.font-weight-bold Films seen
        - @user.films_seen.each do |film|
          %p= link_to film.title, film_path(film)
        %h2.font-weight-bold Films to see
        - @user.films_to_see.each do |film|
          %p= link_to film.title, film_path(film)