config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, path: '', path_names: { sign_in: 'login',
              sign_out: 'logout', sign_up: 'register' },
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friendships, only: %i[create update destroy]
  resources :films, only: %i[index show] do
    resources :reviews, only: %i[index show new create]
  end
  resources :people, only: [:show]
  resources :news
  resources :libraries
  resources :users, only: %i[index show]

  mount ActionCable.server => '/cable'
end

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  -# -key == 'notice' ? key = 'info' : key = 'notice'
  %div{class: "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    = value

app/views/shared/_nav.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  .container
    %a.navbar-brand{:href => root_path } RAILS-FILMS
    %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarCollapse.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li= link_to "FILMS", films_path, class: 'nav-link'
        %li= link_to "NEWS", news_index_path, class: 'nav-link'
        %li= link_to "USERS", users_path, class: 'nav-link' if user_signed_in?
      %ul.navbar-nav.ml-auto
        - if user_signed_in?
          = render 'shared/notifications', user: current_user
          %li.nav-item.dropdown
            %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle"   => "dropdown", :href => "https://example.com"}
              = current_user.name
            .dropdown-menu{"aria-labelledby" => "dropdown01"}
              = link_to "Profile", current_user, class: 'dropdown-item'
              = link_to "Edit profile", edit_user_registration_path, class: 'dropdown-item'
              = link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item'
          %li.nav-item
            = gravatar_for(current_user, size: 40)
        - else
          %li.nav-item
          = link_to "Register", new_user_registration_path, class: 'nav-link'
          %li.nav-item
          = link_to "Login", new_user_session_path, class: 'nav-link'
          %li.nav-item
            = link_to "Login with Facebook", user_facebook_omniauth_authorize_path, class: 'nav-link'

app/views/shared/_notifications.html.haml
%li.nav-item.dropdown
  %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle"   => "dropdown", :href => "https://example.com"}
    Notifications
  .dropdown-menu{"aria-labelledby" => "dropdown01"}
    - if !user.friendship_requests.empty?
      - user.friendship_requests.each do |request|
        .dropdown-item
          = link_to request.user.name, request.user
          |
          = link_to "Accept", friendship_path(id: request.id), method: :put, class: 'text-success'
          = link_to "Decline", friendship_path(id: request.id), method: :delete, class: 'text-danger'
    - else
      %p.text-center Nothing new