config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, path: '', path_names: { sign_in: 'login',
              sign_out: 'logout', sign_up: 'register' },
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friendships, only: %i[create update destroy]
  resources :films, only: %i[index show] do
    resources :reviews, only: %i[index show new create]
  end
  resources :people, only: [:show]
  resources :news
  resources :libraries
  resources :users, only: %i[index show]

  mount ActionCable.server => '/cable'
end

app/models/news.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: news
#
#  id         :bigint(8)        not null, primary key
#  heading    :string
#  body       :text
#  user_id    :bigint(8)
#  film_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class News < ApplicationRecord
  validates :heading, :body, presence: true

  has_many :comments, dependent: :destroy

  belongs_to :user
  belongs_to :film
end

app/controllers/news_controller.rb
# frozen_string_literal: true

class NewsController < ApplicationController
  access all: %i[show index], %i[admin editor] => :all

  def index
    @news = NewsQuery.new.ordered_by_creation_time.page(params[:page]).per(6)
  end

  def show
    @news = News.includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def new
    @news = News.new
  end

  def create
    @news = current_user.news.new(news_params)
    if @news.save
      redirect_to @news
    else
      render 'new'
    end
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update_attributes(news_params)
      redirect_to @news
    else
      render 'edit'
    end
  end

  private

  def news_params
    params.require(:news).permit(:heading, :body, :user_id, :film_id)
  end
end

app/helpers/news_helper.rb
# frozen_string_literal: true

module NewsHelper
  def markdown(text)
    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true
    }
    renderer = Redcarpet::Render::HTML.new(filter_html: true, hard_wrap: true)
    markdown_to_html = Redcarpet::Markdown.new(renderer, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/news/_form.html.haml
= form_for news do |form|
  .form-group
    = form.text_field :heading, placeholder: 'Heading', class: 'form-control'
  .form-group
    = form.text_area :body, rows: 15, placeholder: 'Content', class: 'form-control'
  .form-group
    = form.select :film_id, Film.all.collect { |f| [f.title, f.id] }, { include_blank: "film" }, class: 'form-control'
  .form-group
    = form.submit 'Submit', class: 'btn basic-button'

app/views/news/_news.html.haml
.news-mini
  %h5= link_to news.heading, news
  %p= "#{news.body[0..40]}..."

app/views/news/edit.html.haml
.container
  .news-form
    %h1 Edit news
    = render 'form', news: @news
    = link_to 'Back', news_index_path

app/views/news/index.html.haml
.container
  .news-index
    %h1.text-center
      %strong News
    = paginate @news
    = link_to 'Create news', new_news_path if user_signed_in? && current_user.has_roles?(:editor, :admin)
    - @news.in_groups_of(2, false).each do |group|
      .row
        - group.each do |news|
          .col-md-6
            .card
              .card-body
                .row
                  .col-md-10
                    %h5.card-title= link_to news.heading, news
                    %p.size-80.text-secondary= news.created_at.strftime("on %m/%d/%Y")
                %p.card-text= truncate(strip_tags(markdown(news.body)), length: 250)
                = link_to "Read more", news
    = paginate @news

app/views/news/new.html.haml
.container
  .news-form
    %h1 Create news
    = render 'form', news: @news
    = link_to 'Back', news_index_path

app/views/news/show.html.haml
.container
  .news-show.col-md-9
    %h1= @news.heading
    %p.news-info
      autor:
      = link_to "#{@news.user.name}", user_path(@news.user)
      = "| #{@news.created_at}"
      - if logged_in? && current_user.editor?
        = link_to '| edytuj', edit_news_path(@news)
    .news-body
      %p= markdown(@news.body)
    = render 'comments/comment_form' if user_signed_in?
    #comments{'data-news-id'=>"#{@news.id}"}
      = render @news.comments