config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, path: '', path_names: { sign_in: 'login',
              sign_out: 'logout', sign_up: 'register' },
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friendships, only: %i[create update destroy]
  resources :films, only: %i[index show] do
    resources :reviews, only: %i[index show new create]
  end
  resources :people, only: [:show]
  resources :news
  resources :libraries
  resources :users, only: %i[index show]

  mount ActionCable.server => '/cable'
end

app/models/film.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: films
#
#  id                :bigint(8)        not null, primary key
#  title             :string
#  description       :text
#  short_description :text
#  duration          :integer
#  release           :date
#  production        :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Film < ApplicationRecord
  serialize :production, Array

  validates :title, presence: true, length: { maximum: 50 }
  validates :short_description, length: { maximum: 200 }

  has_and_belongs_to_many :genres, before_add: :check_genres_size
  has_many :employments
  has_many :people, through: :employments
  has_many :actors, -> { Employment.as_actor }, class_name: 'Employment'
  has_many :directors, -> { Employment.as_director }, through: :employments, source: :person
  has_many :screenwriters, -> { Employment.as_screenwriter }, through: :employments, source: :person

  has_many :news
  has_many :reviews

  def check_genres_size genre
    raise ActiveRecord::Rollback if genres.size > 2
  end
end

app/controllers/films_controller.rb
# frozen_string_literal: true

class FilmsController < ApplicationController
  def index
    @q = Film.includes(:directors, actors: :person).ransack(params[:q])
    @films = FilmDecorator.decorate_collection(@q.result.includes(:genres).to_a.uniq)
  end

  def show
    @film = Film.includes(actors: :person).find(params[:id]).decorate
    @library = Library.new
  end
end

app/views/films/_film.html.haml
.single-film
  .col-md-10
    %h3
      %strong
        = link_to film.title, film_path(film), class: 'title-link'
      = "(#{film.release.year})"
    .additional-info
      .row
        .col-md-6
          %span
            %strong Genre:
          %ul
            - film.genres.each do |genre|
              %li= genre.name
        .col-md-6
          %span
            %strong Production:
          %ul
            %li= film.production_list
      .row
        .col-md-6
          %span
            %strong Director:
          %ul
            - film.directors.each do |director|
              %li
                = link_to director.name, person_path(director)
        .col-md-6
          %span
            %strong Cast:
          %ul
            - film.actors.first(2).each do |actor|
              %li
                = link_to actor.person.name, person_path(actor.person)
    .row
      .col-md-12
        = film.short_description

app/views/films/_library_form.html.haml
= form_for @library do |f|

  = f.select :status_id, Status.all.collect { |s| [s.name, s.id] }, class: 'custom-select'
  = f.number_field :user_id, value: current_user.id, readonly: true, hidden: true
  = f.number_field :film_id, value: @film.id, readonly: true, hidden: true


  = f.submit "Save", class: 'btn basic-button'

app/views/films/index.html.haml
.container
  .films-index
    %h1.text-center
      %strong Films
    .row
      .col-md-8
        = render @films
      .col-md-4
        .col-md-4.text-center
        %h2.text-center Filter results
        = search_form_for @q, html: {class: 'films-filters'} do |f|
          .filter-title
            = f.label :title_cont, class: 'sr-only'
            = f.search_field :title_cont, placeholder: "Title includes", class: 'form-control'
          .filter-genre
            = f.select :genres_name_in, Genre.list_genres, { include_blank: "All genres" }, class: 'form-control'
          .filter-premiere.form-group
            = f.date_select :release_gteq, {prompt: "Year from", start_year: Time.now.year, end_year: 1888, order: [:year], }, class: 'form-control form-control-sm'
            = f.date_select :release_year_lteq, {prompt: "Year to", start_year: Time.now.year, end_year: 1888, order: [:year], }, class: 'form-control form-control-sm'
          = f.submit "Filter", class: 'filter-button btn'

app/views/films/show.html.haml
.container
  .film-page
    .row
      .col-md-8.film-details
        %h1
          = @film.title
          %span.half-size= "(#{@film.year})"
        %p= @film.calculated_duration
        %p= @film.short_description
        %table
          %tbody
            %tr
              %th director:
              %td
                - @film.directors.each do |director|
                  =link_to director.name, person_path(director)
            %tr
              %th screenwriter:
              %td
                - @film.screenwriters.each do |screenwriter|
                  =link_to screenwriter.name, person_path(screenwriter)
            %tr
              %th genre:
              %td
                = @film.genres_list
            %tr
              %th prodution:
              %td
                = @film.production_list
            %tr
              %th release:
              %td
                = @film.release
      .col-md-4.rating-panel
        - if !user_signed_in?
          %p
            = link_to 'Log in', new_user_session_path
            = ' to add films to library'
        - else
          - if current_user.films.include?(@film)
            - @library = current_user.libraries.where(film: @film).first
            %h4 In library
            = button_to "Remove from library", library_path(@library), method: :delete, class: 'btn btn-danger'
          = render 'library_form'
        .rating-stats
          = fa_icon "star", class: "fa-3x"
          %span.rating= @film.average_rating
          %span.rating-count
            = pluralize(@film.reviews.size, 'vote')
    .row
      .col-md-8
        %h3 Film description
        %p= @film.description
        .film-cast
          %h3 cast
          - @film.actors.each_with_index do |actor, index|
            .row
              .col-md-3
                %p
                  = link_to actor.person.name, person_path(actor.person)
              .col-md-2.role-as
                - if index == 0
                  = 'as: '
              .col-md-3
                %p= actor.job_details
            %hr
        .film-news
          %h3 Recent news
          .row
            - @film.news.last(2).each do |n|
              .col-md-6
                %h4
                  = link_to n.heading, n
                %p= truncate(strip_tags(markdown(n.body)), length: 40)
      .col-md-4
        %h3
          Recent reviews
          |
          = link_to 'See all', film_reviews_path(@film)
        %p= link_to 'Write your review', new_film_review_path(@film) if user_signed_in? && current_user.film_review(@film).empty?
        - @film.reviews.last(3).each do |r|
          .review
            %h5= link_to r.user.name, user_path(r.user)
            %p= "Rating: #{r.rating}"
            %p= "#{r.body[0...40]}..."
            = link_to 'Read more', film_review_path(r.film, r)